[wandb]
project = "rot|sac_quadrotors"
group = ""
entity = "lsy-tum"

[env]
name = "DroneFigureEightTrajectory-v0"
n_envs = 1024
n_eval_envs = 64

[env.kwargs]
n_samples = 10
trajectory_time = 10.0
physics = "analytical"
freq = 50
device = "gpu"

[env.wrapper.kwargs]
action_type = "tangent"
obs_type = "matrix"
control_mode = "rel"

[sac]
# General params
device = "cuda"
# Rollout params
n_steps = 768_000
# Training params
actor_lr = 0.003
critic_lr = 0.001
buffer_size = 768_000
eps = 1e-8
train_period = 6144
train_steps = 1024
actor_period = 1
critic_period = 1
target_period = 20
tau = 0.02
gamma = 0.975
grad_clip = 2.5
batch_size = 1024
alpha = 0.045
autotune_alpha = true
alpha_lr = 0.03
learning_starts = 0
# Eval params
eval_period = 32_768
eval_steps = 32_000  # 64 * 500
# Checkpoint params
checkpoint_path = "saves/sac"
checkpoint_buffer = false
# Action transform
[[sac.action_tf]]
type = "IdentityTF"

[overrides]
[overrides.tangent-matrix-dense]  # https://wandb.ai/lsy-tum/rot|sac_sweep/runs/4xjd6xax?nw=nwuseru1999168
actor_lr = 1.028e-4
actor_period = 8
alpha = 8.21e-1
alpha_lr = 2.32e-2
batch_size = 4096
critic_lr = 1.03e-3
critic_period = 1
eps = 1.076e-5
gamma = 9.24e-1
target_period = 10
tau = 6.355e-2
train_steps = 1024

[overrides.euler-matrix-dense]  # https://wandb.ai/lsy-tum/rot%7Csac_sweep/sweeps/r1p58czy/runs/0ept9xc2/overview?nw=nwuseramacati
actor_lr = 0.000194
actor_period = 4
alpha = 0.8189
alpha_lr = 0.0571
batch_size = 2048
critic_lr = 0.00749
critic_period = 1
eps = 0.00000229
gamma = 0.913
target_period = 10
tau = 0.0887
train_steps = 1024

[overrides.matrix-matrix-dense]  # https://wandb.ai/lsy-tum/rot%7Csac_sweep/runs/miuesw5v/overview?nw=nwuseramacati
actor_lr = 3.867e-4
actor_period = 4
alpha = 5.1e-1
alpha_lr = 5.38e-2
batch_size = 1024
critic_lr = 8.55e-4
critic_period = 1
eps = 0.00001
gamma = 0.909
target_period = 20
tau = 0.0969
train_steps = 1024

[overrides.quat-matrix-dense]  # https://wandb.ai/lsy-tum/rot%7Csac_sweep/sweeps/7p9n9qgj/runs/erc2fdp7/overview?nw=nwuseramacati
actor_lr = 2.1e-4
actor_period = 2
alpha = 3.07e-1
alpha_lr = 0.0272
batch_size = 4096
critic_lr = 0.00182
critic_period = 1
eps = 0.0000185
gamma = 0.944
target_period = 10
tau = 0.029
train_steps = 1024
