[wandb]
project = "rot|td3_robosuite"
group = ""
entity = "lsy-tum"

[env]
name = "Lift"
n_envs = 8
actor_class = "manipulator"
[env.kwargs]
robots = ["Panda"]
gripper_types = "default"
use_camera_obs = false
use_object_obs = true
reward_scale = 1.0
reward_shaping = true
has_renderer = false
has_offscreen_renderer = false
control_freq = 20
horizon = 500
ignore_done = false
hard_reset = false

[env.wrapper.kwargs]
action_type = "tangent"
obs_type = "matrix"
control_mode = "rel"

[td3]
# General params
device = "cuda"
# Rollout params
n_steps = 1_000_000
# Training params
actor_lr = 0.001
critic_lr = 0.0005
buffer_size = 1_000_000
train_period = 2_500
train_steps = 1_000
actor_period = 1
critic_period = 1
actor_target_period = 10
critic_target_period = 10
tau = 0.005
gamma = 0.99
grad_clip = 5.0
batch_size = 128
# Eval params
eval_period = 20_000
eval_steps = 8_000      # Deviation from benchmark (2_500)
# Checkpoint params
checkpoint_path = "saves/robosuite/td3"
checkpoint_buffer = false
# checkpoint_period = 1_280 
# overwrite_policy = false
# Action transform -> Uniform Noise with probability 0.3 and clipping to [-1.0, 1.0]
[[td3.action_tf]]
type = "ChoiceTF"
[td3.action_tf.kwargs]
prob = [0.7, 0.3]
[[td3.action_tf.kwargs.transforms]]
type = "IdentityTF"
[[td3.action_tf.kwargs.transforms]]
type = "ReplaceWithNoiseTF"
[td3.action_tf.kwargs.transforms.kwargs.noise]
type = "UniformNoise"
[td3.action_tf.kwargs.transforms.kwargs.noise.kwargs]
min = -1.0
max = 1.0
[[td3.action_tf]]
type = "ClipTF"
[td3.action_tf.kwargs]
min = -1.0
max = 1.0
# Target action transform: Gaussian noise with mean 0.0 and std 0.2#
[[td3.target_action_tf]]
type = "AdditiveNoiseTF"
[td3.target_action_tf.kwargs.noise]
type = "NormalNoise"
[td3.target_action_tf.kwargs.noise.kwargs]
mean = 0.0
std = 0.1
# No eval action transform or train action transform

# Environment-specific overrides
[overrides.Wipe]
actor_class = "pose"
gripper_types = "WipingGripper"

[overrides.TwoArmLift]
actor_class = "dual_manipulator"
robots = ["Panda", "Panda"]

[overrides.TwoArmHandover]
actor_class = "dual_manipulator"
robots = ["Panda", "Panda"]

[overrides.TwoArmPegInHole]
actor_class = "dual_pose"
robots = ["Panda", "Panda"]
gripper_types = "none"
